managed-keys-zone: loaded serial 0
zone 0.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone example.com/IN: loaded serial 2016050204
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
all zones loaded
running
zone example.com/IN: sending notifies (serial 2016050204)
no longer listening on 192.168.64.10#53
listening on IPv4 interface ens33, 192.168.64.10#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:503:eea3::30#53
error (network unreachable) resolving 'github.com/A/IN': 2001:503:eea3::30#53
error (network unreachable) resolving 'ns2.p16.dynect.net/A/IN': 2001:503:d2d::30#53
error (network unreachable) resolving 'ns2.p16.dynect.net/A/IN': 2001:503:39c1::30#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/A/IN': 2001:500:c::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/AAAA/IN': 2001:500:c::1#53
error (network unreachable) resolving 'ns-1707.awsdns-21.co.uk/A/IN': 2600:9000:5303:9500::1#53
error (network unreachable) resolving 'ns-1707.awsdns-21.co.uk/A/IN': 2600:9000:5307:1900::1#53
error (network unreachable) resolving 'ns-1707.awsdns-21.co.uk/A/IN': 2600:9000:5301:5500::1#53
error (network unreachable) resolving 'ns-1707.awsdns-21.co.uk/A/IN': 2600:9000:5305:d800::1#53
error (network unreachable) resolving 'ns2.p16.dynect.net/A/IN': 2600:2000:1001::21#53
error (network unreachable) resolving 'ns1.p16.dynect.net/A/IN': 2a02:e180:8::1#53
error (network unreachable) resolving 'ns1.p16.dynect.net/AAAA/IN': 2a02:e180:8::1#53
error (network unreachable) resolving 'ns-520.awsdns-01.net/A/IN': 2600:9000:5307:8100::1#53
error (network unreachable) resolving 'ns-520.awsdns-01.net/AAAA/IN': 2600:9000:5307:8100::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/A/IN': 2600:9000:5306:6000::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/AAAA/IN': 2600:9000:5306:6000::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/A/IN': 2600:9000:5302:e200::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/AAAA/IN': 2600:9000:5302:e200::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/A/IN': 2600:9000:5304:2300::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/AAAA/IN': 2600:9000:5304:2300::1#53
error (network unreachable) resolving 'github.com/A/IN': 2600:9000:5305:300::1#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2600:9000:5305:300::1#53
error (network unreachable) resolving 'github.com/DS/IN': 2001:503:a83e::2:30#53
error (network unreachable) resolving 'github.com/A/IN': 2600:9000:5306:ab00::1#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.64.10#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 2
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone example.com/IN: loaded serial 2016050204
zone localhost.localdomain/IN: loaded serial 0
all zones loaded
running
zone example.com/IN: sending notifies (serial 2016050204)
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.64.10#53
exiting
managed-keys-zone: loaded serial 2
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone example.com/IN: loaded serial 2016050204
zone 64.168.192.in-addr.arpa/IN: loaded serial 2000121201
zone localhost.localdomain/IN: loaded serial 0
all zones loaded
running
zone example.com/IN: sending notifies (serial 2016050204)
zone 64.168.192.in-addr.arpa/IN: sending notifies (serial 2000121201)
error (network unreachable) resolving 'andup/A/IN': 2001:500:2d::d#53
error (network unreachable) resolving 'andup/A/IN': 2001:500:2f::f#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:9f::42#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.64.10#53
exiting
managed-keys-zone: loaded serial 2
zone 0.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 64.168.192.in-addr.arpa/IN: loaded serial 2000121201
zone localhost/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone example.com/IN: loaded serial 2016050204
all zones loaded
running
zone 64.168.192.in-addr.arpa/IN: sending notifies (serial 2000121201)
zone example.com/IN: sending notifies (serial 2016050204)
error (network unreachable) resolving 'github.com/A/IN': 2001:500:12::d0d#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:500:12::d0d#53
error (network unreachable) resolving './NS/IN': 2001:500:9f::42#53
error (network unreachable) resolving './NS/IN': 2001:7fd::1#53
error (network unreachable) resolving 'github.com/A/IN': 2001:500:9f::42#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:500:9f::42#53
error (network unreachable) resolving './NS/IN': 2001:500:2::c#53
error (network unreachable) resolving './NS/IN': 2001:7fe::53#53
error (network unreachable) resolving './NS/IN': 2001:dc3::35#53
error (network unreachable) resolving 'github.com/A/IN': 2001:7fd::1#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:7fd::1#53
error (network unreachable) resolving 'github.com/A/IN': 2001:500:2::c#53
error (network unreachable) resolving './NS/IN': 2001:500:84::b#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:500:2::c#53
error (network unreachable) resolving 'github.com/A/IN': 2001:7fe::53#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:7fe::53#53
error (network unreachable) resolving 'github.com/A/IN': 2001:dc3::35#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:dc3::35#53
error (network unreachable) resolving 'github.com/A/IN': 2001:500:84::b#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:500:84::b#53
error (network unreachable) resolving 'github.com/AAAA/IN': 2001:502:1ca1::30#53
error (network unreachable) resolving 'ns1.p16.dynect.net/A/IN': 2001:503:39c1::30#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'ns-1707.awsdns-21.co.uk/AAAA/IN': 2a01:618:404::1#53
error (network unreachable) resolving 'ns-1707.awsdns-21.co.uk/AAAA/IN': 2401:fd80:404::1#53
error (network unreachable) resolving 'ns-1283.awsdns-32.org/A/IN': 2600:9000:5304:2300::1#53
error (network unreachable) resolving 'ns1.p16.dynect.net/A/IN': 2600:2000:1000::21#53
error (network unreachable) resolving 'github.com/A/IN': 2600:9000:5306:ab00::1#53
error (network unreachable) resolving 'github.com/A/IN': 2600:9000:5305:300::1#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.64.10#53
exiting
managed-keys-zone: loaded serial 2
zone 0.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone 64.168.192.in-addr.arpa/IN: loaded serial 2000121201
zone example.com/IN: loaded serial 2016050204
all zones loaded
running
zone example.com/IN: sending notifies (serial 2016050204)
zone 64.168.192.in-addr.arpa/IN: sending notifies (serial 2000121201)
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.64.10#53
exiting
managed-keys-zone: journal file is out of date: removing journal file
managed-keys-zone: loaded serial 3
zone 0.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone example.com/IN: loaded serial 2016050204
zone 64.168.192.in-addr.arpa/IN: loaded serial 2000121201
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
all zones loaded
running
zone example.com/IN: sending notifies (serial 2016050204)
zone 64.168.192.in-addr.arpa/IN: sending notifies (serial 2000121201)
error (network unreachable) resolving './DNSKEY/IN': 2001:500:a8::e#53
error (network unreachable) resolving 'ns2.p20.dynect.net/A/IN': 2001:500:856e::30#53
error (network unreachable) resolving 'ns2.p20.dynect.net/AAAA/IN': 2001:500:856e::30#53
error (network unreachable) resolving 'a.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'a.ntpns.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'b.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'b.ntpns.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'c.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'c.ntpns.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'd.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'd.ntpns.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'e.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'e.ntpns.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'f.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'f.ntpns.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'g.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'g.ntpns.org/AAAA/IN': 2001:500:b::1#53
error (network unreachable) resolving 'h.ntpns.org/A/IN': 2001:500:b::1#53
error (network unreachable) resolving 'h.ntpns.org/AAAA/IN': 2001:500:b::1#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.64.10#53
exiting
managed-keys-zone: loaded serial 3
zone 0.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
zone example.com/IN: loaded serial 2016050204
zone 64.168.192.in-addr.arpa/IN: loaded serial 2000121201
zone localhost/IN: loaded serial 0
all zones loaded
running
zone example.com/IN: sending notifies (serial 2016050204)
zone 64.168.192.in-addr.arpa/IN: sending notifies (serial 2000121201)
error (network unreachable) resolving './DNSKEY/IN': 2001:503:c27::2:30#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:2f::f#53
error (network unreachable) resolving './DNSKEY/IN': 2001:500:9f::42#53
error (network unreachable) resolving './DNSKEY/IN': 2001:503:ba3e::2:30#53
received control channel command 'stop'
shutting down: flushing changes
stopping command channel on 127.0.0.1#953
stopping command channel on ::1#953
no longer listening on 127.0.0.1#53
no longer listening on 192.168.64.10#53
exiting
managed-keys-zone: loaded serial 3
zone 0.in-addr.arpa/IN: loaded serial 0
zone localhost/IN: loaded serial 0
zone 64.168.192.in-addr.arpa/IN: loaded serial 2000121201
zone 1.0.0.127.in-addr.arpa/IN: loaded serial 0
zone localhost.localdomain/IN: loaded serial 0
zone example.com/IN: loaded serial 2016050204
zone 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa/IN: loaded serial 0
all zones loaded
running
zone example.com/IN: sending notifies (serial 2016050204)
zone 64.168.192.in-addr.arpa/IN: sending notifies (serial 2000121201)
